enum MessageTypes {
  // * Server Side Types
  CREDENTIALS_REQUEST = "CREDENTIALS_REQUEST",
  
  GAME_TEAMS_UPDATE = "GAME_TEAMS_UPDATE",

  // *Client Side Types
  CREDENTIALS = "CREDENTIALS",

  CREDENTIALS_SUCCESS = "CREDENTIALS_SUCCESS",
  CEREDENTIALS_FAIL = "CEREDENTIALS_FAIL",

  CREATE_TEAM = "CREATE_TEAM",

  // * Error Types
  ERR_MALFORMED_REQUEST = "ERR_MALFORMED_REQUEST",
  ERR_NO_CREDENTIALS = "ERR_NO_CREDENTIALS",
  ERR_UNAUTHORIZED = "ERR_UNAUTHORIZED",
  ERR_INVALID_GAMEID = "ERR_INVALID_GAMEID"
}

export { MessageTypes };
