enum WebSocketMessage {
    // * Server Side Types
  CREDENTIALS_REQUEST = "CREDENTIALS_REQUEST",

  // *Client Side Types
  CREDENTIALS = "CREDENTIALS",

  CREDENTIALS_SUCCESS = "CREDENTIALS_SUCCESS",
  CEREDENTIALS_FAIL = "CEREDENTIALS_FAIL",

  // * Error Types
  ERR_MALFORMED_REQUEST = "ERR_MALFORMED_REQUEST",
  ERR_NO_CREDENTIALS = "ERR_NO_CREDENTIALS",
  ERR_UNAUTHORIZED = "ERR_UNAUTHORIZED",
  ERR_INVALID_GAMEID = "ERR_INVALID_GAMEID"
}

export {WebSocketMessage}